apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "web-app-chart.fullname" . }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "web-app-chart.fullname" . }}-web-app
  template:
    metadata:
      labels:
        app: {{ template "web-app-chart.fullname" . }}-web-app
        type: front-end
    spec:
      containers:
        - name: web-app
          image: mozmut/simple-webapp:latest
          ports:
            - containerPort: 8090

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "web-app-chart.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ template "web-app-chart.fullname" . }}-web-app
    type: front-end
  ports:
    - targetPort: 8090
      port: 8090
      nodePort: 30008